---
# adapted from https://www.epilis.gr/en/blog/2017/08/09/extending-root-fs-whole-farm/
# NOTE: vars vg_name and lv_name are different when using Red Hat, CentOS or other Linux distro
- name: Extend root partition to fill all available space
  hosts: all
  vars:
    dev: /dev/sda
    vg_name: rl_rocky
    lv_name: root
  tasks:
  - name: install parted
    dnf: 
      name: "parted" 
      state: present
  - name: Get partition information
    community.general.parted:
      device: "{{dev}}"
    register: partinfo
  - debug: var=partinfo.partitions[-1].end
  - name: "Create a new partition after {{partinfo.partitions[-1].end}}KiB"
    community.general.parted:
      part_start: "{{partinfo.partitions[-1].end}}KiB"
      device: "{{dev}}"
      label: gpt
      number: "{{partinfo.partitions[-1].num + 1}}"
      flags: [ lvm ]
      state: present
  - name: Probe kernel about partition table changes
    command: partprobe
  - name: Add the partition to the volume group
    lvg:
      vg: "{{vg_name}}"
      pvs: "{{dev}}{{partinfo.partitions[-1].num}},{{dev}}{{partinfo.partitions[-1].num + 1}}"
  - name: Extend LVM to the whole volume group
    lvol:
      vg: "{{vg_name}}"
      lv: "{{lv_name}}"
      size: +100%FREE
  - name: Extend the filesystem
    filesystem:
      fstype: xfs
      dev: "/dev/mapper/{{vg_name}}-{{lv_name}}"
      resizefs: yes
