---
- name: Install and start httpd
  hosts: all

  tasks:
  - name: install package httpd
    yum:
      name: httpd
      state: latest

  - name: Enable service httpd and ensure it is not masked
    ansible.builtin.systemd:
      name: httpd
      enabled: yes
      masked: no

  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: httpd

  - name: Open HTTP and HTTPS services
    ansible.builtin.shell: |
      firewall-cmd --add-service=http
      firewall-cmd --add-service=https
      firewall-cmd --runtime-to-permanent

